#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CL_ModHook

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CL_ModHook.BP_CL_ModHook_C
// 0x0028 (0x0050 - 0x0028)
class UBP_CL_ModHook_C final : public UModHook
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0028(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<class UObject*>                        AllAssetObjects;                                   // 0x0030(0x0010)(Edit, BlueprintVisible)
	TArray<class UClass*>                         AllAssetClasses;                                   // 0x0040(0x0010)(Edit, BlueprintVisible)

public:
	void ExecuteUbergraph_BP_CL_ModHook(int32 EntryPoint);
	void PostSpawnVehicle(class ABrickVehicle* Vehicle);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CL_ModHook_C">();
	}
	static class UBP_CL_ModHook_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CL_ModHook_C>();
	}
};
static_assert(alignof(UBP_CL_ModHook_C) == 0x000008, "Wrong alignment on UBP_CL_ModHook_C");
static_assert(sizeof(UBP_CL_ModHook_C) == 0x000050, "Wrong size on UBP_CL_ModHook_C");
static_assert(offsetof(UBP_CL_ModHook_C, UberGraphFrame) == 0x000028, "Member 'UBP_CL_ModHook_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_CL_ModHook_C, AllAssetObjects) == 0x000030, "Member 'UBP_CL_ModHook_C::AllAssetObjects' has a wrong offset!");
static_assert(offsetof(UBP_CL_ModHook_C, AllAssetClasses) == 0x000040, "Member 'UBP_CL_ModHook_C::AllAssetClasses' has a wrong offset!");

}

