#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CL_ModHook

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_CL_ModHook.BP_CL_ModHook_C.ExecuteUbergraph_BP_CL_ModHook
// 0x00C8 (0x00C8 - 0x0000)
struct BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABrickVehicle*                          K2Node_Event_Vehicle;                              // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IAssetRegistry>        CallFunc_GetAssetRegistry_ReturnValue;             // 0x0018(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper)
	TArray<struct FAssetData>                     CallFunc_GetAllAssets_OutAssetData;                // 0x0028(0x0010)(ReferenceParm)
	bool                                          CallFunc_GetAllAssets_ReturnValue;                 // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAssetData                             CallFunc_Array_Get_Item;                           // 0x0040(0x0060)(HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A4[0x4];                                       // 0x00A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_GetClass_ReturnValue;                     // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B1[0x3];                                       // 0x00B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                CallFunc_GetAsset_ReturnValue;                     // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_1;                  // 0x00C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook) == 0x000008, "Wrong alignment on BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook");
static_assert(sizeof(BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook) == 0x0000C8, "Wrong size on BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook");
static_assert(offsetof(BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook, EntryPoint) == 0x000000, "Member 'BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook, Temp_int_Array_Index_Variable) == 0x000004, "Member 'BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook, Temp_int_Loop_Counter_Variable) == 0x000008, "Member 'BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook, CallFunc_Add_IntInt_ReturnValue) == 0x00000C, "Member 'BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook, K2Node_Event_Vehicle) == 0x000010, "Member 'BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook::K2Node_Event_Vehicle' has a wrong offset!");
static_assert(offsetof(BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook, CallFunc_GetAssetRegistry_ReturnValue) == 0x000018, "Member 'BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook::CallFunc_GetAssetRegistry_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook, CallFunc_GetAllAssets_OutAssetData) == 0x000028, "Member 'BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook::CallFunc_GetAllAssets_OutAssetData' has a wrong offset!");
static_assert(offsetof(BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook, CallFunc_GetAllAssets_ReturnValue) == 0x000038, "Member 'BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook::CallFunc_GetAllAssets_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook, CallFunc_Array_Get_Item) == 0x000040, "Member 'BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook, CallFunc_Array_Length_ReturnValue) == 0x0000A0, "Member 'BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook, CallFunc_GetClass_ReturnValue) == 0x0000A8, "Member 'BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook::CallFunc_GetClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook, CallFunc_Less_IntInt_ReturnValue) == 0x0000B0, "Member 'BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook, CallFunc_Array_Add_ReturnValue) == 0x0000B4, "Member 'BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook, CallFunc_GetAsset_ReturnValue) == 0x0000B8, "Member 'BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook::CallFunc_GetAsset_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook, CallFunc_Array_Add_ReturnValue_1) == 0x0000C0, "Member 'BP_CL_ModHook_C_ExecuteUbergraph_BP_CL_ModHook::CallFunc_Array_Add_ReturnValue_1' has a wrong offset!");

// Function BP_CL_ModHook.BP_CL_ModHook_C.PostSpawnVehicle
// 0x0008 (0x0008 - 0x0000)
struct BP_CL_ModHook_C_PostSpawnVehicle final
{
public:
	class ABrickVehicle*                          Vehicle;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CL_ModHook_C_PostSpawnVehicle) == 0x000008, "Wrong alignment on BP_CL_ModHook_C_PostSpawnVehicle");
static_assert(sizeof(BP_CL_ModHook_C_PostSpawnVehicle) == 0x000008, "Wrong size on BP_CL_ModHook_C_PostSpawnVehicle");
static_assert(offsetof(BP_CL_ModHook_C_PostSpawnVehicle, Vehicle) == 0x000000, "Member 'BP_CL_ModHook_C_PostSpawnVehicle::Vehicle' has a wrong offset!");

}

