#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_JerseyBarrier

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_JerseyBarrier.BP_JerseyBarrier_C
// 0x0000 (0x0240 - 0x0240)
class ABP_JerseyBarrier_C final : public AStaticMeshProp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_JerseyBarrier_C">();
	}
	static class ABP_JerseyBarrier_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_JerseyBarrier_C>();
	}
};
static_assert(alignof(ABP_JerseyBarrier_C) == 0x000008, "Wrong alignment on ABP_JerseyBarrier_C");
static_assert(sizeof(ABP_JerseyBarrier_C) == 0x000240, "Wrong size on ABP_JerseyBarrier_C");

}

