#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MK18

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MK18.BP_MK18_C
// 0x0000 (0x02B0 - 0x02B0)
class ABP_MK18_C final : public AFirearm
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MK18_C">();
	}
	static class ABP_MK18_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MK18_C>();
	}
};
static_assert(alignof(ABP_MK18_C) == 0x000008, "Wrong alignment on ABP_MK18_C");
static_assert(sizeof(ABP_MK18_C) == 0x0002B0, "Wrong size on ABP_MK18_C");

}

