#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RC_Sequence_2

#include "Basic.hpp"

#include "BP_RC_Sequence_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_RC_Sequence_2.BP_RC_Sequence_2_C
// 0x0008 (0x02A0 - 0x0298)
class ABP_RC_Sequence_2_C : public ABP_RC_Sequence_C
{
public:
	class USkeletalMeshComponent*                 Parent;                                            // 0x0298(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	struct FVector GetHandTargetLocation() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_RC_Sequence_2_C">();
	}
	static class ABP_RC_Sequence_2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RC_Sequence_2_C>();
	}
};
static_assert(alignof(ABP_RC_Sequence_2_C) == 0x000008, "Wrong alignment on ABP_RC_Sequence_2_C");
static_assert(sizeof(ABP_RC_Sequence_2_C) == 0x0002A0, "Wrong size on ABP_RC_Sequence_2_C");
static_assert(offsetof(ABP_RC_Sequence_2_C, Parent) == 0x000298, "Member 'ABP_RC_Sequence_2_C::Parent' has a wrong offset!");

}

