#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SandboxGameMode

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SandboxGameMode.BP_SandboxGameMode_C
// 0x0008 (0x0450 - 0x0448)
class ABP_SandboxGameMode_C final : public ASandboxGameMode
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0448(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SandboxGameMode_C">();
	}
	static class ABP_SandboxGameMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SandboxGameMode_C>();
	}
};
static_assert(alignof(ABP_SandboxGameMode_C) == 0x000008, "Wrong alignment on ABP_SandboxGameMode_C");
static_assert(sizeof(ABP_SandboxGameMode_C) == 0x000450, "Wrong size on ABP_SandboxGameMode_C");
static_assert(offsetof(ABP_SandboxGameMode_C, DefaultSceneRoot) == 0x000448, "Member 'ABP_SandboxGameMode_C::DefaultSceneRoot' has a wrong offset!");

}

