#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Tank_Projectile

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Tank_Projectile.BP_Tank_Projectile_C
// 0x0000 (0x0400 - 0x0400)
class ABP_Tank_Projectile_C final : public ABrickProjectile
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Tank_Projectile_C">();
	}
	static class ABP_Tank_Projectile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Tank_Projectile_C>();
	}
};
static_assert(alignof(ABP_Tank_Projectile_C) == 0x000010, "Wrong alignment on ABP_Tank_Projectile_C");
static_assert(sizeof(ABP_Tank_Projectile_C) == 0x000400, "Wrong size on ABP_Tank_Projectile_C");

}

