#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UIStyle_Blue

#include "Basic.hpp"

#include "BP_UIStyle_Default_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_UIStyle_Blue.BP_UIStyle_Blue_C
// 0x0008 (0x7100 - 0x70F8)
class UBP_UIStyle_Blue_C final : public UBP_UIStyle_Default_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_UIStyle_Blue_C;                  // 0x70F8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_UIStyle_Blue(int32 EntryPoint);
	void BuildStyle();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_UIStyle_Blue_C">();
	}
	static class UBP_UIStyle_Blue_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_UIStyle_Blue_C>();
	}
};
static_assert(alignof(UBP_UIStyle_Blue_C) == 0x000008, "Wrong alignment on UBP_UIStyle_Blue_C");
static_assert(sizeof(UBP_UIStyle_Blue_C) == 0x007100, "Wrong size on UBP_UIStyle_Blue_C");
static_assert(offsetof(UBP_UIStyle_Blue_C, UberGraphFrame_BP_UIStyle_Blue_C) == 0x0070F8, "Member 'UBP_UIStyle_Blue_C::UberGraphFrame_BP_UIStyle_Blue_C' has a wrong offset!");

}

