#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_VehicleEditor

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_VehicleEditor.BP_VehicleEditor_C
// 0x0000 (0x0538 - 0x0538)
class ABP_VehicleEditor_C final : public AVehicleEditor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_VehicleEditor_C">();
	}
	static class ABP_VehicleEditor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_VehicleEditor_C>();
	}
};
static_assert(alignof(ABP_VehicleEditor_C) == 0x000008, "Wrong alignment on ABP_VehicleEditor_C");
static_assert(sizeof(ABP_VehicleEditor_C) == 0x000538, "Wrong size on ABP_VehicleEditor_C");

}

