#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Vehicle_Sequence

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "InputCore_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_Vehicle_Sequence.BP_Vehicle_Sequence_C.ExecuteUbergraph_BP_Vehicle_Sequence
// 0x03E0 (0x03E0 - 0x0000)
struct BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x0004(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class USeatBrick*                             CallFunc_GetDriverSeat_ReturnValue;                // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x001C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FKey                                   K2Node_InputActionEvent_Key;                       // 0x0030(0x0018)(HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_K2_GetComponentToWorld_ReturnValue;       // 0x0050(0x0030)(IsPlainOldData, NoDestructor)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_1;        // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_BrickVehicle_C*                     CallFunc_FinishSpawningActor_ReturnValue;          // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_GetHitResultUnderCursorByChannel_HitResult; // 0x0098(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_GetHitResultUnderCursorByChannel_ReturnValue; // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x0121(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x0122(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_123[0x1];                                      // 0x0123(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x0124(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x0128(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x012C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x0138(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x0144(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x0150(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_15C[0x4];                                      // 0x015C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x0160(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x0168(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x0170(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x0178(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x0180(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x0184(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x0188(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x018C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x0198(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1A4[0x4];                                      // 0x01A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UPrimitiveComponent*>            K2Node_MakeArray_Array;                            // 0x01A8(0x0010)(ConstParm, ReferenceParm, ContainsInstancedReference)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x01B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1B9[0x7];                                      // 0x01B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FUGCFileInfo>                   K2Node_Event_FileInfos;                            // 0x01C0(0x0010)(ConstParm, ReferenceParm)
	struct FUGCFileInfo                           CallFunc_Array_Random_OutItem;                     // 0x01D0(0x00E8)()
	int32                                         CallFunc_Array_Random_OutIndex;                    // 0x02B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_K2_GetComponentRotation_ReturnValue;      // 0x02BC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x02C8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2D4[0x4];                                      // 0x02D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UBrick*>                         CallFunc_GetBricks_ReturnValue;                    // 0x02D8(0x0010)(ConstParm, ReferenceParm)
	uint8                                         Pad_2E8[0x8];                                      // 0x02E8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_K2_GetComponentToWorld_ReturnValue_1;     // 0x02F0(0x0030)(IsPlainOldData, NoDestructor)
	class UBrickVehicleComponent*                 CallFunc_GetVehicleComponent_ReturnValue;          // 0x0320(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_2;        // 0x0328(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABrickCameraManager*                    K2Node_DynamicCast_AsBrick_Camera_Manager;         // 0x0330(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0338(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_339[0x3];                                      // 0x0339(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              CallFunc_GetEffectiveFOV_ReturnValue;              // 0x033C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_FocusCameraOnBrickEditorObjects_ReturnValue; // 0x0344(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetWorldLocation_SweepHitResult;       // 0x0350(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence) == 0x000010, "Wrong alignment on BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence");
static_assert(sizeof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence) == 0x0003E0, "Wrong size on BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, EntryPoint) == 0x000000, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_MakeRotator_ReturnValue) == 0x000004, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_GetDriverSeat_ReturnValue) == 0x000010, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_GetDriverSeat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_IsValid_ReturnValue) == 0x000018, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, K2Node_CreateDelegate_OutputDelegate) == 0x00001C, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, K2Node_InputActionEvent_Key) == 0x000030, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::K2Node_InputActionEvent_Key' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_GetPlayerController_ReturnValue) == 0x000048, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_K2_GetComponentToWorld_ReturnValue) == 0x000050, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_K2_GetComponentToWorld_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x000080, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_GetPlayerController_ReturnValue_1) == 0x000088, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_GetPlayerController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_FinishSpawningActor_ReturnValue) == 0x000090, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_GetHitResultUnderCursorByChannel_HitResult) == 0x000098, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_GetHitResultUnderCursorByChannel_HitResult' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_GetHitResultUnderCursorByChannel_ReturnValue) == 0x000120, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_GetHitResultUnderCursorByChannel_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_BreakHitResult_bBlockingHit) == 0x000121, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_BreakHitResult_bInitialOverlap) == 0x000122, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_BreakHitResult_Time) == 0x000124, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_BreakHitResult_Distance) == 0x000128, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_BreakHitResult_Location) == 0x00012C, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_BreakHitResult_ImpactPoint) == 0x000138, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_BreakHitResult_Normal) == 0x000144, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_BreakHitResult_ImpactNormal) == 0x000150, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_BreakHitResult_PhysMat) == 0x000160, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_BreakHitResult_HitActor) == 0x000168, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_BreakHitResult_HitComponent) == 0x000170, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_BreakHitResult_HitBoneName) == 0x000178, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_BreakHitResult_HitItem) == 0x000180, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_BreakHitResult_ElementIndex) == 0x000184, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_BreakHitResult_FaceIndex) == 0x000188, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_BreakHitResult_TraceStart) == 0x00018C, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_BreakHitResult_TraceEnd) == 0x000198, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, K2Node_MakeArray_Array) == 0x0001A8, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x0001B8, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, K2Node_Event_FileInfos) == 0x0001C0, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::K2Node_Event_FileInfos' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_Array_Random_OutItem) == 0x0001D0, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_Array_Random_OutItem' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_Array_Random_OutIndex) == 0x0002B8, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_Array_Random_OutIndex' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_K2_GetComponentRotation_ReturnValue) == 0x0002BC, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_K2_GetComponentRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x0002C8, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_GetBricks_ReturnValue) == 0x0002D8, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_GetBricks_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_K2_GetComponentToWorld_ReturnValue_1) == 0x0002F0, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_K2_GetComponentToWorld_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_GetVehicleComponent_ReturnValue) == 0x000320, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_GetVehicleComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_GetPlayerController_ReturnValue_2) == 0x000328, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_GetPlayerController_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, K2Node_DynamicCast_AsBrick_Camera_Manager) == 0x000330, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::K2Node_DynamicCast_AsBrick_Camera_Manager' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, K2Node_DynamicCast_bSuccess) == 0x000338, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_GetEffectiveFOV_ReturnValue) == 0x00033C, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_GetEffectiveFOV_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_FocusCameraOnBrickEditorObjects_ReturnValue) == 0x000344, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_FocusCameraOnBrickEditorObjects_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence, CallFunc_K2_SetWorldLocation_SweepHitResult) == 0x000350, "Member 'BP_Vehicle_Sequence_C_ExecuteUbergraph_BP_Vehicle_Sequence::CallFunc_K2_SetWorldLocation_SweepHitResult' has a wrong offset!");

// Function BP_Vehicle_Sequence.BP_Vehicle_Sequence_C.OnDefaultVehiclesQueried
// 0x0010 (0x0010 - 0x0000)
struct BP_Vehicle_Sequence_C_OnDefaultVehiclesQueried final
{
public:
	TArray<struct FUGCFileInfo>                   FileInfos;                                         // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(BP_Vehicle_Sequence_C_OnDefaultVehiclesQueried) == 0x000008, "Wrong alignment on BP_Vehicle_Sequence_C_OnDefaultVehiclesQueried");
static_assert(sizeof(BP_Vehicle_Sequence_C_OnDefaultVehiclesQueried) == 0x000010, "Wrong size on BP_Vehicle_Sequence_C_OnDefaultVehiclesQueried");
static_assert(offsetof(BP_Vehicle_Sequence_C_OnDefaultVehiclesQueried, FileInfos) == 0x000000, "Member 'BP_Vehicle_Sequence_C_OnDefaultVehiclesQueried::FileInfos' has a wrong offset!");

// Function BP_Vehicle_Sequence.BP_Vehicle_Sequence_C.InpActEvt_Fire_K2Node_InputActionEvent_0
// 0x0018 (0x0018 - 0x0000)
struct BP_Vehicle_Sequence_C_InpActEvt_Fire_K2Node_InputActionEvent_0 final
{
public:
	struct FKey                                   Key;                                               // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
static_assert(alignof(BP_Vehicle_Sequence_C_InpActEvt_Fire_K2Node_InputActionEvent_0) == 0x000008, "Wrong alignment on BP_Vehicle_Sequence_C_InpActEvt_Fire_K2Node_InputActionEvent_0");
static_assert(sizeof(BP_Vehicle_Sequence_C_InpActEvt_Fire_K2Node_InputActionEvent_0) == 0x000018, "Wrong size on BP_Vehicle_Sequence_C_InpActEvt_Fire_K2Node_InputActionEvent_0");
static_assert(offsetof(BP_Vehicle_Sequence_C_InpActEvt_Fire_K2Node_InputActionEvent_0, Key) == 0x000000, "Member 'BP_Vehicle_Sequence_C_InpActEvt_Fire_K2Node_InputActionEvent_0::Key' has a wrong offset!");

// Function BP_Vehicle_Sequence.BP_Vehicle_Sequence_C.IsMenuSequenceReady
// 0x0001 (0x0001 - 0x0000)
struct BP_Vehicle_Sequence_C_IsMenuSequenceReady final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Vehicle_Sequence_C_IsMenuSequenceReady) == 0x000001, "Wrong alignment on BP_Vehicle_Sequence_C_IsMenuSequenceReady");
static_assert(sizeof(BP_Vehicle_Sequence_C_IsMenuSequenceReady) == 0x000001, "Wrong size on BP_Vehicle_Sequence_C_IsMenuSequenceReady");
static_assert(offsetof(BP_Vehicle_Sequence_C_IsMenuSequenceReady, ReturnValue) == 0x000000, "Member 'BP_Vehicle_Sequence_C_IsMenuSequenceReady::ReturnValue' has a wrong offset!");

}

