#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Vehicle_Sequence

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Vehicle_Sequence.BP_Vehicle_Sequence_C
// 0x0038 (0x0288 - 0x0250)
class ABP_Vehicle_Sequence_C final : public AMenuSequence
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0250(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   ResetButton;                                       // 0x0258(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        SpawnPoint;                                        // 0x0260(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCameraComponent*                       Camera;                                            // 0x0268(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0270(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class ABP_BrickVehicle_C*                     Vehicle;                                           // 0x0278(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bVehicleReady;                                     // 0x0280(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_BP_Vehicle_Sequence(int32 EntryPoint);
	void RepairVehicle();
	void OnVehicleConstructed();
	void OnDefaultVehiclesQueried(const TArray<struct FUGCFileInfo>& FileInfos);
	void ReceiveBeginPlay();
	void InpActEvt_Fire_K2Node_InputActionEvent_0(const struct FKey& Key);

	bool IsMenuSequenceReady() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Vehicle_Sequence_C">();
	}
	static class ABP_Vehicle_Sequence_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Vehicle_Sequence_C>();
	}
};
static_assert(alignof(ABP_Vehicle_Sequence_C) == 0x000008, "Wrong alignment on ABP_Vehicle_Sequence_C");
static_assert(sizeof(ABP_Vehicle_Sequence_C) == 0x000288, "Wrong size on ABP_Vehicle_Sequence_C");
static_assert(offsetof(ABP_Vehicle_Sequence_C, UberGraphFrame) == 0x000250, "Member 'ABP_Vehicle_Sequence_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_Vehicle_Sequence_C, ResetButton) == 0x000258, "Member 'ABP_Vehicle_Sequence_C::ResetButton' has a wrong offset!");
static_assert(offsetof(ABP_Vehicle_Sequence_C, SpawnPoint) == 0x000260, "Member 'ABP_Vehicle_Sequence_C::SpawnPoint' has a wrong offset!");
static_assert(offsetof(ABP_Vehicle_Sequence_C, Camera) == 0x000268, "Member 'ABP_Vehicle_Sequence_C::Camera' has a wrong offset!");
static_assert(offsetof(ABP_Vehicle_Sequence_C, DefaultSceneRoot) == 0x000270, "Member 'ABP_Vehicle_Sequence_C::DefaultSceneRoot' has a wrong offset!");
static_assert(offsetof(ABP_Vehicle_Sequence_C, Vehicle) == 0x000278, "Member 'ABP_Vehicle_Sequence_C::Vehicle' has a wrong offset!");
static_assert(offsetof(ABP_Vehicle_Sequence_C, bVehicleReady) == 0x000280, "Member 'ABP_Vehicle_Sequence_C::bVehicleReady' has a wrong offset!");

}

