#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BT_City

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BT_City.BT_City_C
// 0x0000 (0x0228 - 0x0228)
class ABT_City_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BT_City_C">();
	}
	static class ABT_City_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABT_City_C>();
	}
};
static_assert(alignof(ABT_City_C) == 0x000008, "Wrong alignment on ABT_City_C");
static_assert(sizeof(ABT_City_C) == 0x000228, "Wrong size on ABT_City_C");

}

