#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Canyon

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Canyon.Canyon_C
// 0x0000 (0x0228 - 0x0228)
class ACanyon_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Canyon_C">();
	}
	static class ACanyon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACanyon_C>();
	}
};
static_assert(alignof(ACanyon_C) == 0x000008, "Wrong alignment on ACanyon_C");
static_assert(sizeof(ACanyon_C) == 0x000228, "Wrong size on ACanyon_C");

}

