#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: City

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass City.City_C
// 0x0000 (0x0228 - 0x0228)
class ACity_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"City_C">();
	}
	static class ACity_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACity_C>();
	}
};
static_assert(alignof(ACity_C) == 0x000008, "Wrong alignment on ACity_C");
static_assert(sizeof(ACity_C) == 0x000228, "Wrong size on ACity_C");

}

