#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CQ_City2

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CQ_City2.CQ_City2_C
// 0x0000 (0x0228 - 0x0228)
class ACQ_City2_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CQ_City2_C">();
	}
	static class ACQ_City2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACQ_City2_C>();
	}
};
static_assert(alignof(ACQ_City2_C) == 0x000008, "Wrong alignment on ACQ_City2_C");
static_assert(sizeof(ACQ_City2_C) == 0x000228, "Wrong size on ACQ_City2_C");

}

