#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CQ_City

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CQ_City.CQ_City_C
// 0x0000 (0x0228 - 0x0228)
class ACQ_City_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CQ_City_C">();
	}
	static class ACQ_City_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACQ_City_C>();
	}
};
static_assert(alignof(ACQ_City_C) == 0x000008, "Wrong alignment on ACQ_City_C");
static_assert(sizeof(ACQ_City_C) == 0x000228, "Wrong size on ACQ_City_C");

}

