#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Desert

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Desert.Desert_C
// 0x0008 (0x0230 - 0x0228)
class ADesert_C final : public ALevelScriptActor
{
public:
	bool                                          NewVar;                                            // 0x0228(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Desert_C">();
	}
	static class ADesert_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADesert_C>();
	}
};
static_assert(alignof(ADesert_C) == 0x000008, "Wrong alignment on ADesert_C");
static_assert(sizeof(ADesert_C) == 0x000230, "Wrong size on ADesert_C");
static_assert(offsetof(ADesert_C, NewVar) == 0x000228, "Member 'ADesert_C::NewVar' has a wrong offset!");

}

