#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ENiagara_WrapClamp

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum ENiagara_WrapClamp.ENiagara_WrapClamp
// NumValues: 0x0003
enum class ENiagara_WrapClamp : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	ENiagara_MAX                             = 2,
};

}

