#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ENiagara_MassInitializationMode

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum ENiagara_MassInitializationMode.ENiagara_MassInitializationMode
// NumValues: 0x0004
enum class ENiagara_MassInitializationMode : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator3                           = 2,
	ENiagara_MAX                             = 3,
};

}

