#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ENiagaraSphereDistributionMode

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum ENiagaraSphereDistributionMode.ENiagaraSphereDistributionMode
// NumValues: 0x0004
enum class ENiagaraSphereDistributionMode : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator3                           = 2,
	ENiagaraSphereDistributionMode_MAX       = 3,
};

}

