#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ENiagara_SubUVLookupMode

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum ENiagara_SubUVLookupMode.ENiagara_SubUVLookupMode
// NumValues: 0x0005
enum class ENiagara_SubUVLookupMode : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	ENiagara_MAX                             = 4,
};

}

