#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FluUGCSteam

#include "Basic.hpp"

#include "FluUGC_classes.hpp"


namespace SDK
{

// Class FluUGCSteam.FluUGCSubsystemSteam
// 0x0008 (0x0068 - 0x0060)
class UFluUGCSubsystemSteam final : public UFluUGCSubsystem
{
public:
	uint8                                         Pad_60[0x8];                                       // 0x0060(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FluUGCSubsystemSteam">();
	}
	static class UFluUGCSubsystemSteam* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFluUGCSubsystemSteam>();
	}
};
static_assert(alignof(UFluUGCSubsystemSteam) == 0x000008, "Wrong alignment on UFluUGCSubsystemSteam");
static_assert(sizeof(UFluUGCSubsystemSteam) == 0x000068, "Wrong size on UFluUGCSubsystemSteam");

}

