#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GridMap

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GridMap.GridMap_C
// 0x0000 (0x0228 - 0x0228)
class AGridMap_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GridMap_C">();
	}
	static class AGridMap_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGridMap_C>();
	}
};
static_assert(alignof(AGridMap_C) == 0x000008, "Wrong alignment on AGridMap_C");
static_assert(sizeof(AGridMap_C) == 0x000228, "Wrong size on AGridMap_C");

}

