#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RaceOval

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RaceOval.RaceOval_C
// 0x0000 (0x0228 - 0x0228)
class ARaceOval_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"RaceOval_C">();
	}
	static class ARaceOval_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ARaceOval_C>();
	}
};
static_assert(alignof(ARaceOval_C) == 0x000008, "Wrong alignment on ARaceOval_C");
static_assert(sizeof(ARaceOval_C) == 0x000228, "Wrong size on ARaceOval_C");

}

