#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Spectator

#include "Basic.hpp"

#include "BrickRigs_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function WBP_Spectator.WBP_Spectator_C.ExecuteUbergraph_WBP_Spectator
// 0x00D0 (0x00D0 - 0x0000)
struct WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable;                                // 0x0008(0x0018)(ConstParm)
	class FText                                   K2Node_Event_PlayerName;                           // 0x0020(0x0018)(ConstParm)
	bool                                          K2Node_Event_bIsValidPlayer;                       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0040(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0080(0x0010)(ReferenceParm)
	EBrickUIColorStyle                            K2Node_ComponentBoundEvent_InColorStyle_1;         // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIStyleState                            K2Node_ComponentBoundEvent_InContentStyleState_1;  // 0x0091(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_92[0x6];                                       // 0x0092(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0098(0x0018)()
	EBrickUIColorStyle                            K2Node_ComponentBoundEvent_InColorStyle;           // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIStyleState                            K2Node_ComponentBoundEvent_InContentStyleState;    // 0x00B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B2[0x6];                                       // 0x00B2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Select_Default;                             // 0x00B8(0x0018)(ConstParm)
};
static_assert(alignof(WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator) == 0x000008, "Wrong alignment on WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator");
static_assert(sizeof(WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator) == 0x0000D0, "Wrong size on WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator");
static_assert(offsetof(WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator, EntryPoint) == 0x000000, "Member 'WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator, Temp_bool_Variable) == 0x000004, "Member 'WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator, Temp_text_Variable) == 0x000008, "Member 'WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator::Temp_text_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator, K2Node_Event_PlayerName) == 0x000020, "Member 'WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator::K2Node_Event_PlayerName' has a wrong offset!");
static_assert(offsetof(WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator, K2Node_Event_bIsValidPlayer) == 0x000038, "Member 'WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator::K2Node_Event_bIsValidPlayer' has a wrong offset!");
static_assert(offsetof(WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator, K2Node_MakeStruct_FormatArgumentData) == 0x000040, "Member 'WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator, K2Node_MakeArray_Array) == 0x000080, "Member 'WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator, K2Node_ComponentBoundEvent_InColorStyle_1) == 0x000090, "Member 'WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator::K2Node_ComponentBoundEvent_InColorStyle_1' has a wrong offset!");
static_assert(offsetof(WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator, K2Node_ComponentBoundEvent_InContentStyleState_1) == 0x000091, "Member 'WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator::K2Node_ComponentBoundEvent_InContentStyleState_1' has a wrong offset!");
static_assert(offsetof(WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator, CallFunc_Format_ReturnValue) == 0x000098, "Member 'WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator, K2Node_ComponentBoundEvent_InColorStyle) == 0x0000B0, "Member 'WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator::K2Node_ComponentBoundEvent_InColorStyle' has a wrong offset!");
static_assert(offsetof(WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator, K2Node_ComponentBoundEvent_InContentStyleState) == 0x0000B1, "Member 'WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator::K2Node_ComponentBoundEvent_InContentStyleState' has a wrong offset!");
static_assert(offsetof(WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator, K2Node_Select_Default) == 0x0000B8, "Member 'WBP_Spectator_C_ExecuteUbergraph_WBP_Spectator::K2Node_Select_Default' has a wrong offset!");

// Function WBP_Spectator.WBP_Spectator_C.BndEvt__NextPlayerButton_K2Node_ComponentBoundEvent_3_OnUpdateContentStyle__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct WBP_Spectator_C_BndEvt__NextPlayerButton_K2Node_ComponentBoundEvent_3_OnUpdateContentStyle__DelegateSignature final
{
public:
	EBrickUIColorStyle                            InColorStyle;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIStyleState                            InContentStyleState;                               // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Spectator_C_BndEvt__NextPlayerButton_K2Node_ComponentBoundEvent_3_OnUpdateContentStyle__DelegateSignature) == 0x000001, "Wrong alignment on WBP_Spectator_C_BndEvt__NextPlayerButton_K2Node_ComponentBoundEvent_3_OnUpdateContentStyle__DelegateSignature");
static_assert(sizeof(WBP_Spectator_C_BndEvt__NextPlayerButton_K2Node_ComponentBoundEvent_3_OnUpdateContentStyle__DelegateSignature) == 0x000002, "Wrong size on WBP_Spectator_C_BndEvt__NextPlayerButton_K2Node_ComponentBoundEvent_3_OnUpdateContentStyle__DelegateSignature");
static_assert(offsetof(WBP_Spectator_C_BndEvt__NextPlayerButton_K2Node_ComponentBoundEvent_3_OnUpdateContentStyle__DelegateSignature, InColorStyle) == 0x000000, "Member 'WBP_Spectator_C_BndEvt__NextPlayerButton_K2Node_ComponentBoundEvent_3_OnUpdateContentStyle__DelegateSignature::InColorStyle' has a wrong offset!");
static_assert(offsetof(WBP_Spectator_C_BndEvt__NextPlayerButton_K2Node_ComponentBoundEvent_3_OnUpdateContentStyle__DelegateSignature, InContentStyleState) == 0x000001, "Member 'WBP_Spectator_C_BndEvt__NextPlayerButton_K2Node_ComponentBoundEvent_3_OnUpdateContentStyle__DelegateSignature::InContentStyleState' has a wrong offset!");

// Function WBP_Spectator.WBP_Spectator_C.BndEvt__PrevPlayerButton_K2Node_ComponentBoundEvent_2_OnUpdateContentStyle__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct WBP_Spectator_C_BndEvt__PrevPlayerButton_K2Node_ComponentBoundEvent_2_OnUpdateContentStyle__DelegateSignature final
{
public:
	EBrickUIColorStyle                            InColorStyle;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIStyleState                            InContentStyleState;                               // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Spectator_C_BndEvt__PrevPlayerButton_K2Node_ComponentBoundEvent_2_OnUpdateContentStyle__DelegateSignature) == 0x000001, "Wrong alignment on WBP_Spectator_C_BndEvt__PrevPlayerButton_K2Node_ComponentBoundEvent_2_OnUpdateContentStyle__DelegateSignature");
static_assert(sizeof(WBP_Spectator_C_BndEvt__PrevPlayerButton_K2Node_ComponentBoundEvent_2_OnUpdateContentStyle__DelegateSignature) == 0x000002, "Wrong size on WBP_Spectator_C_BndEvt__PrevPlayerButton_K2Node_ComponentBoundEvent_2_OnUpdateContentStyle__DelegateSignature");
static_assert(offsetof(WBP_Spectator_C_BndEvt__PrevPlayerButton_K2Node_ComponentBoundEvent_2_OnUpdateContentStyle__DelegateSignature, InColorStyle) == 0x000000, "Member 'WBP_Spectator_C_BndEvt__PrevPlayerButton_K2Node_ComponentBoundEvent_2_OnUpdateContentStyle__DelegateSignature::InColorStyle' has a wrong offset!");
static_assert(offsetof(WBP_Spectator_C_BndEvt__PrevPlayerButton_K2Node_ComponentBoundEvent_2_OnUpdateContentStyle__DelegateSignature, InContentStyleState) == 0x000001, "Member 'WBP_Spectator_C_BndEvt__PrevPlayerButton_K2Node_ComponentBoundEvent_2_OnUpdateContentStyle__DelegateSignature::InContentStyleState' has a wrong offset!");

// Function WBP_Spectator.WBP_Spectator_C.UpdateSpectatedPlayer
// 0x0020 (0x0020 - 0x0000)
struct WBP_Spectator_C_UpdateSpectatedPlayer final
{
public:
	class FText                                   PlayerName;                                        // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	bool                                          bIsValidPlayer;                                    // 0x0018(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_Spectator_C_UpdateSpectatedPlayer) == 0x000008, "Wrong alignment on WBP_Spectator_C_UpdateSpectatedPlayer");
static_assert(sizeof(WBP_Spectator_C_UpdateSpectatedPlayer) == 0x000020, "Wrong size on WBP_Spectator_C_UpdateSpectatedPlayer");
static_assert(offsetof(WBP_Spectator_C_UpdateSpectatedPlayer, PlayerName) == 0x000000, "Member 'WBP_Spectator_C_UpdateSpectatedPlayer::PlayerName' has a wrong offset!");
static_assert(offsetof(WBP_Spectator_C_UpdateSpectatedPlayer, bIsValidPlayer) == 0x000018, "Member 'WBP_Spectator_C_UpdateSpectatedPlayer::bIsValidPlayer' has a wrong offset!");

// Function WBP_Spectator.WBP_Spectator_C.GetWidgetToFocus
// 0x0008 (0x0008 - 0x0000)
struct WBP_Spectator_C_GetWidgetToFocus final
{
public:
	class UWidget*                                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Spectator_C_GetWidgetToFocus) == 0x000008, "Wrong alignment on WBP_Spectator_C_GetWidgetToFocus");
static_assert(sizeof(WBP_Spectator_C_GetWidgetToFocus) == 0x000008, "Wrong size on WBP_Spectator_C_GetWidgetToFocus");
static_assert(offsetof(WBP_Spectator_C_GetWidgetToFocus, ReturnValue) == 0x000000, "Member 'WBP_Spectator_C_GetWidgetToFocus::ReturnValue' has a wrong offset!");

}

