#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InputKey

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "BrickRigs_structs.hpp"


namespace SDK::Params
{

// Function WBP_InputKey.WBP_InputKey_C.ExecuteUbergraph_WBP_InputKey
// 0x0048 (0x0048 - 0x0000)
struct WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EBrickUIIconAtlas                             Temp_byte_Variable;                                // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBrickUIIconAtlas                             Temp_byte_Variable_1;                              // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_2;                              // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_3;                              // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x000B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FKeyDisplayTableRow                    K2Node_Event_DisplayInfo;                          // 0x0010(0x0028)(ConstParm)
	bool                                          K2Node_Event_bIsGamepadKey;                        // 0x0038(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	EBrickUIIconAtlas                             K2Node_Select_Default_1;                           // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A[0x2];                                       // 0x003A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBrickUIIconSlot                       K2Node_MakeStruct_BrickUIIconSlot;                 // 0x003C(0x0008)(NoDestructor)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey) == 0x000008, "Wrong alignment on WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey");
static_assert(sizeof(WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey) == 0x000048, "Wrong size on WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey");
static_assert(offsetof(WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey, EntryPoint) == 0x000000, "Member 'WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey, Temp_bool_Variable) == 0x000004, "Member 'WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000005, "Member 'WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey, Temp_byte_Variable) == 0x000006, "Member 'WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey, Temp_byte_Variable_1) == 0x000007, "Member 'WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey, Temp_bool_Variable_1) == 0x000008, "Member 'WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey, Temp_byte_Variable_2) == 0x000009, "Member 'WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey, Temp_byte_Variable_3) == 0x00000A, "Member 'WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey::Temp_byte_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey, K2Node_Select_Default) == 0x00000B, "Member 'WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey, K2Node_Event_DisplayInfo) == 0x000010, "Member 'WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey::K2Node_Event_DisplayInfo' has a wrong offset!");
static_assert(offsetof(WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey, K2Node_Event_bIsGamepadKey) == 0x000038, "Member 'WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey::K2Node_Event_bIsGamepadKey' has a wrong offset!");
static_assert(offsetof(WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey, K2Node_Select_Default_1) == 0x000039, "Member 'WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey, K2Node_MakeStruct_BrickUIIconSlot) == 0x00003C, "Member 'WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey::K2Node_MakeStruct_BrickUIIconSlot' has a wrong offset!");
static_assert(offsetof(WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x000044, "Member 'WBP_InputKey_C_ExecuteUbergraph_WBP_InputKey::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");

// Function WBP_InputKey.WBP_InputKey_C.UpdateKey
// 0x0030 (0x0030 - 0x0000)
struct WBP_InputKey_C_UpdateKey final
{
public:
	struct FKeyDisplayTableRow                    DisplayInfo;                                       // 0x0000(0x0028)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	bool                                          bIsGamepadKey;                                     // 0x0028(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(WBP_InputKey_C_UpdateKey) == 0x000008, "Wrong alignment on WBP_InputKey_C_UpdateKey");
static_assert(sizeof(WBP_InputKey_C_UpdateKey) == 0x000030, "Wrong size on WBP_InputKey_C_UpdateKey");
static_assert(offsetof(WBP_InputKey_C_UpdateKey, DisplayInfo) == 0x000000, "Member 'WBP_InputKey_C_UpdateKey::DisplayInfo' has a wrong offset!");
static_assert(offsetof(WBP_InputKey_C_UpdateKey, bIsGamepadKey) == 0x000028, "Member 'WBP_InputKey_C_UpdateKey::bIsGamepadKey' has a wrong offset!");

}

