#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MapMarker

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MapMarker.WBP_MapMarker_C
// 0x0008 (0x0268 - 0x0260)
class UWBP_MapMarker_C final : public UUserWidget
{
public:
	class UBrickImage*                            BrickImage_45;                                     // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MapMarker_C">();
	}
	static class UWBP_MapMarker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MapMarker_C>();
	}
};
static_assert(alignof(UWBP_MapMarker_C) == 0x000008, "Wrong alignment on UWBP_MapMarker_C");
static_assert(sizeof(UWBP_MapMarker_C) == 0x000268, "Wrong size on UWBP_MapMarker_C");
static_assert(offsetof(UWBP_MapMarker_C, BrickImage_45) == 0x000260, "Member 'UWBP_MapMarker_C::BrickImage_45' has a wrong offset!");

}

