#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_NewItemCount

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_NewItemCount.WBP_NewItemCount_C.ExecuteUbergraph_WBP_NewItemCount
// 0x0060 (0x0060 - 0x0000)
struct WBP_NewItemCount_C_ExecuteUbergraph_WBP_NewItemCount final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_NewNum;                               // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0010(0x0018)()
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable;                                // 0x0030(0x0018)()
	class FText                                   K2Node_Select_Default;                             // 0x0048(0x0018)()
};
static_assert(alignof(WBP_NewItemCount_C_ExecuteUbergraph_WBP_NewItemCount) == 0x000008, "Wrong alignment on WBP_NewItemCount_C_ExecuteUbergraph_WBP_NewItemCount");
static_assert(sizeof(WBP_NewItemCount_C_ExecuteUbergraph_WBP_NewItemCount) == 0x000060, "Wrong size on WBP_NewItemCount_C_ExecuteUbergraph_WBP_NewItemCount");
static_assert(offsetof(WBP_NewItemCount_C_ExecuteUbergraph_WBP_NewItemCount, EntryPoint) == 0x000000, "Member 'WBP_NewItemCount_C_ExecuteUbergraph_WBP_NewItemCount::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_NewItemCount_C_ExecuteUbergraph_WBP_NewItemCount, K2Node_Event_NewNum) == 0x000004, "Member 'WBP_NewItemCount_C_ExecuteUbergraph_WBP_NewItemCount::K2Node_Event_NewNum' has a wrong offset!");
static_assert(offsetof(WBP_NewItemCount_C_ExecuteUbergraph_WBP_NewItemCount, Temp_bool_Variable) == 0x000008, "Member 'WBP_NewItemCount_C_ExecuteUbergraph_WBP_NewItemCount::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_NewItemCount_C_ExecuteUbergraph_WBP_NewItemCount, CallFunc_Conv_IntToText_ReturnValue) == 0x000010, "Member 'WBP_NewItemCount_C_ExecuteUbergraph_WBP_NewItemCount::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_NewItemCount_C_ExecuteUbergraph_WBP_NewItemCount, CallFunc_Greater_IntInt_ReturnValue) == 0x000028, "Member 'WBP_NewItemCount_C_ExecuteUbergraph_WBP_NewItemCount::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_NewItemCount_C_ExecuteUbergraph_WBP_NewItemCount, Temp_text_Variable) == 0x000030, "Member 'WBP_NewItemCount_C_ExecuteUbergraph_WBP_NewItemCount::Temp_text_Variable' has a wrong offset!");
static_assert(offsetof(WBP_NewItemCount_C_ExecuteUbergraph_WBP_NewItemCount, K2Node_Select_Default) == 0x000048, "Member 'WBP_NewItemCount_C_ExecuteUbergraph_WBP_NewItemCount::K2Node_Select_Default' has a wrong offset!");

// Function WBP_NewItemCount.WBP_NewItemCount_C.UpdateNumItems
// 0x0004 (0x0004 - 0x0000)
struct WBP_NewItemCount_C_UpdateNumItems final
{
public:
	int32                                         NewNum;                                            // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_NewItemCount_C_UpdateNumItems) == 0x000004, "Wrong alignment on WBP_NewItemCount_C_UpdateNumItems");
static_assert(sizeof(WBP_NewItemCount_C_UpdateNumItems) == 0x000004, "Wrong size on WBP_NewItemCount_C_UpdateNumItems");
static_assert(offsetof(WBP_NewItemCount_C_UpdateNumItems, NewNum) == 0x000000, "Member 'WBP_NewItemCount_C_UpdateNumItems::NewNum' has a wrong offset!");

}

