#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UGCBrowser

#include "Basic.hpp"

#include "FluUGC_structs.hpp"
#include "Engine_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_UGCBrowser.WBP_UGCBrowser_C
// 0x0048 (0x03B0 - 0x0368)
class UWBP_UGCBrowser_C final : public UUGCBrowserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0368(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	EPlayerSpawnResult                            Can_Spawn_Result;                                  // 0x0370(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_371[0x3];                                      // 0x0371(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Num_Bricks;                                        // 0x0374(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVehicleSpawnProperties                SpawnProps;                                        // 0x0378(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	bool                                          Can_Spawn;                                         // 0x0390(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_391[0x7];                                      // 0x0391(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Spawn_Failure_Text;                                // 0x0398(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	bool GetSpawnButtonTooltipContent(struct FTooltipContent* OutContent);
	void CreateClearItemsButton(bool bIsArrayProperty);
	void CreateDeleteButton();
	void CreateDuplicateButton();
	void CreateEditButton();
	void CreateFavoriteButton(bool bIsFavorited);
	void CreateNewItemButton();
	void CreateSpawnButton(bool bCanReplaceCurrent, bool bCanSpawn, const class FText& SpawnFailureText);
	void CreateSubscribeButton(bool bIsSubscribed);
	void CreateViewInBrowserButton();
	void CreateVoteButtons(const EFluUGCItemVote Vote);
	void VoteUp();
	void CreateCancelButton();
	void OnClickedCancel();
	void OnClickedSubscribe();
	void OnClickedUnsubscribe();
	void OnClickedFavorite();
	void OnClickedUnfavorite();
	void CreateImportButton();
	void OnClickedSpawnNew();
	void OnClickedReplaceCurrent();
	void CreateRecoverAutoSaveButton();
	void CreateUploadNewButton();
	void CreateUpdateExistingButton();
	void OnClickedUploadNew();
	void OnClickedUpdateExisting();
	void CreateSaveNewButton();
	void CreateSaveOverwriteButton();
	void OnClickedSaveNew();
	void OnClickedSaveOverwrite();
	void CreateOpenInExplorerButton();
	void CreateSpawnInvincibilityButton(const class FText& CurrentInvincibilityText);
	void CreateAddOrRemoveItemButton(bool bIsArrayProperty, bool bIsSelected);
	void AddItem();
	void RemoveItem();
	void VoteDown();
	void ExecuteUbergraph_WBP_UGCBrowser(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_UGCBrowser_C">();
	}
	static class UWBP_UGCBrowser_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UGCBrowser_C>();
	}
};
static_assert(alignof(UWBP_UGCBrowser_C) == 0x000008, "Wrong alignment on UWBP_UGCBrowser_C");
static_assert(sizeof(UWBP_UGCBrowser_C) == 0x0003B0, "Wrong size on UWBP_UGCBrowser_C");
static_assert(offsetof(UWBP_UGCBrowser_C, UberGraphFrame) == 0x000368, "Member 'UWBP_UGCBrowser_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_UGCBrowser_C, Can_Spawn_Result) == 0x000370, "Member 'UWBP_UGCBrowser_C::Can_Spawn_Result' has a wrong offset!");
static_assert(offsetof(UWBP_UGCBrowser_C, Num_Bricks) == 0x000374, "Member 'UWBP_UGCBrowser_C::Num_Bricks' has a wrong offset!");
static_assert(offsetof(UWBP_UGCBrowser_C, SpawnProps) == 0x000378, "Member 'UWBP_UGCBrowser_C::SpawnProps' has a wrong offset!");
static_assert(offsetof(UWBP_UGCBrowser_C, Can_Spawn) == 0x000390, "Member 'UWBP_UGCBrowser_C::Can_Spawn' has a wrong offset!");
static_assert(offsetof(UWBP_UGCBrowser_C, Spawn_Failure_Text) == 0x000398, "Member 'UWBP_UGCBrowser_C::Spawn_Failure_Text' has a wrong offset!");

}

