#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ComboBoxFadingPanel

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_ComboBoxFadingPanel.WBP_ComboBoxFadingPanel_C
// 0x0010 (0x0298 - 0x0288)
class UWBP_ComboBoxFadingPanel_C final : public UFadingPanelWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0288(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                Border_0;                                          // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_ComboBoxFadingPanel(int32 EntryPoint);
	void UpdateFadeAnimation(float FadeAmount);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_ComboBoxFadingPanel_C">();
	}
	static class UWBP_ComboBoxFadingPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ComboBoxFadingPanel_C>();
	}
};
static_assert(alignof(UWBP_ComboBoxFadingPanel_C) == 0x000008, "Wrong alignment on UWBP_ComboBoxFadingPanel_C");
static_assert(sizeof(UWBP_ComboBoxFadingPanel_C) == 0x000298, "Wrong size on UWBP_ComboBoxFadingPanel_C");
static_assert(offsetof(UWBP_ComboBoxFadingPanel_C, UberGraphFrame) == 0x000288, "Member 'UWBP_ComboBoxFadingPanel_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_ComboBoxFadingPanel_C, Border_0) == 0x000290, "Member 'UWBP_ComboBoxFadingPanel_C::Border_0' has a wrong offset!");

}

