#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Spectator

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Spectator.WBP_Spectator_C
// 0x0030 (0x0298 - 0x0268)
class UWBP_Spectator_C final : public USpectatorWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0268(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_BrickButton_C*                     NextPlayerButton;                                  // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickImage*                            NextPlayerImage;                                   // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickTextBlock*                        PlayerTextBlock;                                   // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_BrickButton_C*                     PrevPlayerButton;                                  // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickImage*                            PrevPlayerImage;                                   // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_Spectator(int32 EntryPoint);
	void BndEvt__NextPlayerButton_K2Node_ComponentBoundEvent_3_OnUpdateContentStyle__DelegateSignature(EBrickUIColorStyle InColorStyle, EBrickUIStyleState InContentStyleState);
	void BndEvt__PrevPlayerButton_K2Node_ComponentBoundEvent_2_OnUpdateContentStyle__DelegateSignature(EBrickUIColorStyle InColorStyle, EBrickUIStyleState InContentStyleState);
	void BndEvt__NextPlayerButton_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature();
	void BndEvt__PrevPlayerButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature();
	void UpdateSpectatedPlayer(const class FText& PlayerName, bool bIsValidPlayer);

	class UWidget* GetWidgetToFocus() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Spectator_C">();
	}
	static class UWBP_Spectator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Spectator_C>();
	}
};
static_assert(alignof(UWBP_Spectator_C) == 0x000008, "Wrong alignment on UWBP_Spectator_C");
static_assert(sizeof(UWBP_Spectator_C) == 0x000298, "Wrong size on UWBP_Spectator_C");
static_assert(offsetof(UWBP_Spectator_C, UberGraphFrame) == 0x000268, "Member 'UWBP_Spectator_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_Spectator_C, NextPlayerButton) == 0x000270, "Member 'UWBP_Spectator_C::NextPlayerButton' has a wrong offset!");
static_assert(offsetof(UWBP_Spectator_C, NextPlayerImage) == 0x000278, "Member 'UWBP_Spectator_C::NextPlayerImage' has a wrong offset!");
static_assert(offsetof(UWBP_Spectator_C, PlayerTextBlock) == 0x000280, "Member 'UWBP_Spectator_C::PlayerTextBlock' has a wrong offset!");
static_assert(offsetof(UWBP_Spectator_C, PrevPlayerButton) == 0x000288, "Member 'UWBP_Spectator_C::PrevPlayerButton' has a wrong offset!");
static_assert(offsetof(UWBP_Spectator_C, PrevPlayerImage) == 0x000290, "Member 'UWBP_Spectator_C::PrevPlayerImage' has a wrong offset!");

}

