#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_NewItemCount

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_NewItemCount.WBP_NewItemCount_C
// 0x0010 (0x0278 - 0x0268)
class UWBP_NewItemCount_C final : public UNewItemCountWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0268(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickTextBlock*                        TextBlock;                                         // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_NewItemCount(int32 EntryPoint);
	void UpdateNumItems(int32 NewNum);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_NewItemCount_C">();
	}
	static class UWBP_NewItemCount_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_NewItemCount_C>();
	}
};
static_assert(alignof(UWBP_NewItemCount_C) == 0x000008, "Wrong alignment on UWBP_NewItemCount_C");
static_assert(sizeof(UWBP_NewItemCount_C) == 0x000278, "Wrong size on UWBP_NewItemCount_C");
static_assert(offsetof(UWBP_NewItemCount_C, UberGraphFrame) == 0x000268, "Member 'UWBP_NewItemCount_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_NewItemCount_C, TextBlock) == 0x000270, "Member 'UWBP_NewItemCount_C::TextBlock' has a wrong offset!");

}

