#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CreditsEntry

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CreditsEntry.WBP_CreditsEntry_C
// 0x0030 (0x0290 - 0x0260)
class UWBP_CreditsEntry_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickRichTextBlock*                    BodyTextBlock;                                     // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickExpandableArea*                   ExpandableArea;                                    // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBrickTextBlock*                        HeaderTextBlock;                                   // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FString                                 LicenseFilename;                                   // 0x0280(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_CreditsEntry(int32 EntryPoint);
	void BndEvt__WBP_CreditsEntry_ExpandableArea_K2Node_ComponentBoundEvent_0_OnExpandableAreaExpansionChanged__DelegateSignature(class UExpandableArea* Area, bool bIsExpanded);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_CreditsEntry_C">();
	}
	static class UWBP_CreditsEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CreditsEntry_C>();
	}
};
static_assert(alignof(UWBP_CreditsEntry_C) == 0x000008, "Wrong alignment on UWBP_CreditsEntry_C");
static_assert(sizeof(UWBP_CreditsEntry_C) == 0x000290, "Wrong size on UWBP_CreditsEntry_C");
static_assert(offsetof(UWBP_CreditsEntry_C, UberGraphFrame) == 0x000260, "Member 'UWBP_CreditsEntry_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_CreditsEntry_C, BodyTextBlock) == 0x000268, "Member 'UWBP_CreditsEntry_C::BodyTextBlock' has a wrong offset!");
static_assert(offsetof(UWBP_CreditsEntry_C, ExpandableArea) == 0x000270, "Member 'UWBP_CreditsEntry_C::ExpandableArea' has a wrong offset!");
static_assert(offsetof(UWBP_CreditsEntry_C, HeaderTextBlock) == 0x000278, "Member 'UWBP_CreditsEntry_C::HeaderTextBlock' has a wrong offset!");
static_assert(offsetof(UWBP_CreditsEntry_C, LicenseFilename) == 0x000280, "Member 'UWBP_CreditsEntry_C::LicenseFilename' has a wrong offset!");

}

