#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ComboBoxFadingPanel

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function WBP_ComboBoxFadingPanel.WBP_ComboBoxFadingPanel_C.ExecuteUbergraph_WBP_ComboBoxFadingPanel
// 0x0010 (0x0010 - 0x0000)
struct WBP_ComboBoxFadingPanel_C_ExecuteUbergraph_WBP_ComboBoxFadingPanel final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_FadeAmount;                           // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue;                 // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_ComboBoxFadingPanel_C_ExecuteUbergraph_WBP_ComboBoxFadingPanel) == 0x000004, "Wrong alignment on WBP_ComboBoxFadingPanel_C_ExecuteUbergraph_WBP_ComboBoxFadingPanel");
static_assert(sizeof(WBP_ComboBoxFadingPanel_C_ExecuteUbergraph_WBP_ComboBoxFadingPanel) == 0x000010, "Wrong size on WBP_ComboBoxFadingPanel_C_ExecuteUbergraph_WBP_ComboBoxFadingPanel");
static_assert(offsetof(WBP_ComboBoxFadingPanel_C_ExecuteUbergraph_WBP_ComboBoxFadingPanel, EntryPoint) == 0x000000, "Member 'WBP_ComboBoxFadingPanel_C_ExecuteUbergraph_WBP_ComboBoxFadingPanel::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_ComboBoxFadingPanel_C_ExecuteUbergraph_WBP_ComboBoxFadingPanel, K2Node_Event_FadeAmount) == 0x000004, "Member 'WBP_ComboBoxFadingPanel_C_ExecuteUbergraph_WBP_ComboBoxFadingPanel::K2Node_Event_FadeAmount' has a wrong offset!");
static_assert(offsetof(WBP_ComboBoxFadingPanel_C_ExecuteUbergraph_WBP_ComboBoxFadingPanel, CallFunc_MakeVector2D_ReturnValue) == 0x000008, "Member 'WBP_ComboBoxFadingPanel_C_ExecuteUbergraph_WBP_ComboBoxFadingPanel::CallFunc_MakeVector2D_ReturnValue' has a wrong offset!");

// Function WBP_ComboBoxFadingPanel.WBP_ComboBoxFadingPanel_C.UpdateFadeAnimation
// 0x0004 (0x0004 - 0x0000)
struct WBP_ComboBoxFadingPanel_C_UpdateFadeAnimation final
{
public:
	float                                         FadeAmount;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_ComboBoxFadingPanel_C_UpdateFadeAnimation) == 0x000004, "Wrong alignment on WBP_ComboBoxFadingPanel_C_UpdateFadeAnimation");
static_assert(sizeof(WBP_ComboBoxFadingPanel_C_UpdateFadeAnimation) == 0x000004, "Wrong size on WBP_ComboBoxFadingPanel_C_UpdateFadeAnimation");
static_assert(offsetof(WBP_ComboBoxFadingPanel_C_UpdateFadeAnimation, FadeAmount) == 0x000000, "Member 'WBP_ComboBoxFadingPanel_C_UpdateFadeAnimation::FadeAmount' has a wrong offset!");

}

