#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Z_City

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Z_City.Z_City_C
// 0x0000 (0x0228 - 0x0228)
class AZ_City_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Z_City_C">();
	}
	static class AZ_City_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AZ_City_C>();
	}
};
static_assert(alignof(AZ_City_C) == 0x000008, "Wrong alignment on AZ_City_C");
static_assert(sizeof(AZ_City_C) == 0x000228, "Wrong size on AZ_City_C");

}

